// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// WARNING: For simplified deployment, these keys are hardcoded.
// For a production environment, it is highly recommended to use
// environment variables to keep these keys secure.
const SUPABASE_URL = "https://jyhimsnvexhmmavvlaxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5aGltc252ZXhobW1hdnZsYXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzIxODEsImV4cCI6MjA3MDE0ODE4MX0.jq1CcPZONgamam6i-k6KOBHvv-Xdl7op0junEkCGrfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});